
insert into users (`id`, `full_name`, `email`, `password`, `phone`, `enabled`, `token_expired`)
values (1, 'normal user', 'user@devotion.com', '{bcrypt}$2a$10$Cyt9Sq8ubL90hVJHqIP0TelSBGBn5sf5nG7p/V0mfD9TTcc8q1kRi', '67882251', true , false ),
(2, 'admin user', 'admin@devotion.com', '{bcrypt}$2a$10$Cyt9Sq8ubL90hVJHqIP0TelSBGBn5sf5nG7p/V0mfD9TTcc8q1kRi', '65412310', true , false );

insert into roles (`id`, `name`)
values (1, 'USER'), (2, 'ADMIN');

insert into privileges (`id`, `name`, `icon`, `displayed`, `uri`)
values (1, 'USER', 'account', true, '/user' ), (2, 'ADMIN', 'key', true, '/admin' );

insert into user_role (`user_id`, `role_id`) values (1, 1), (2, 2);
insert into role_privilege (`role_id`, `privilege_id`) values (1, 1), (2, 1), (2, 2);
/**/
INSERT INTO `countries` (`name`, `iso2`, `iso3`, `num_code`, `phone_code`, `currency_name`, `currency_code`, `lang`,`locale`)
VALUES ('Afghanistan','AF','AFG',4,'93','Afghani','AFN','Uzbek','uz'),
('Aland Islands','AX','xxx','0','xxx','Euro','EUR','English','en'),
('Albania','AL','ALB',8,'355','Lek','ALL','Albanian','sq'),
('Algeria','DZ','DZA',12,'213','Algerian Dinar','DZD','French','fr'),
('American Samoa','AS','ASM',16,'1-684','Euros','EUR','English','en'),
('Andorra','AD','AND',20,'376','Euros','EUR','Catalan','ca'),
('Angola','AO','AGO',24,'244','Angolan kwanza','AOA','Portuguese','pt'),
('Anguilla','AI','AIA',660,'1-264','East Caribbean Dollar','XCD','English','en'),
('Antarctica','AQ','ATA',10,'672','Antarctican dollar','AQD','English','en'),
('Antigua and Barbuda','AG','ATG',28,'1-268','East Caribbean Dollar','XCD','English','en'),
('Argentina','AR','ARG',32,'54','Peso','ARS','Spanish','es'),
('Armenia','AM','ARM',51,'374','Dram','AMD','Armenian','hy'),
('Aruba','AW','ABW',533,'297','Netherlands Antilles Guilder','ANG','English','en'),
('Australia','AU','AUS',36,'61','Australian Dollars','AUD','English','en'),
('Austria','AT','AUT',40,'43','Euros','EUR','German','de'),
('Azerbaijan','AZ','AZE',31,'994','Manat','AZN','English','en'),
('Bahamas','BS','BHS',44,'1-242','Bahamian Dollar','BSD','English','en'),
('Bahrain','BH','BHR',48,'973','Bahraini Dinar','BHD','Arabic','ar'),
('Bangladesh','BD','BGD',50,'880','Taka','BDT','English','en'),
('Barbados','BB','BRB',52,'1-246','Barbadian Dollar','BBD','English','en'),
('Belarus','BY','BLR',112,'375','Belarus Ruble','BYR','Belarusian','be'),
('Belgium','BE','BEL',56,'32','Euros','EUR','French','fr'),
('Belize','BZ','BLZ',84,'501','Belizean Dollar','BZD','English','en'),
('Benin','BJ','BEN',204,'229','CFA Franc BCEAO','XOF','French','fr'),
('Bermuda','BM','BMU',60,'1-441','Bermudian Dollar','BMD','English','en'),
('Bhutan','BT','BTN',64,'975','Indian Rupee','INR','English','en'),
('Bolivia','BO','BOL',68,'591','Boliviano','BOB','Spanish','es'),
('Bosnia and Herzegovina','BA','BIH',70,'387','Bosnia and Herzegovina convertible mark','BAM','Serbian','sr'),
('Botswana','BW','BWA',72,'267','Pula','BWP','English','en'),
('Bouvet Island','BV','BVT',74,'47','Norwegian Krone','NOK','English','en'),
('Brazil','BR','BRA',76,'55','Brazil','BRL','Portuguese','pt'),
('British Indian Ocean Territory','IO','IOT',86,'246','USD','USD','English','en'),
('Brunei Darussalam','BN','BRN',96,'673','Bruneian Dollar','BND','English','en'),
('Bulgaria','BG','BGR',100,'359','Lev','BGN','Bulgarian','bg'),
('Burkina Faso','BF','BFA',854,'226','CFA Franc BCEAO','XOF','French','fr'),
('Burundi','BI','BDI',108,'257','Burundi Franc','BIF','French','fr'),
('Cambodia','KH','KHM',116,'855','Riel','KHR','Khmer','km'),
('Cameroon','CM','CMR',120,'237','CFA Franc BEAC','XAF','English','en'),
('Canada','CA','CAN',124,'1','Canadian Dollar','CAD','English','en'),
('Cape Verde','CV','CPV',132,'238','Escudo','CVE','Portuguese','pt'),
('Cayman Islands','KY','CYM',136,'1-345','Caymanian Dollar','KYD','English','en'),
('Central African Republic','CF','CAF',140,'236','CFA Franc BEAC','XAF','French','fr'),
('Chad','TD','TCD',148,'235','CFA Franc BEAC','XAF','French','fr'),
('Chile','CL','CHL',152,'56','Chilean Peso','CLP','Spanish','es'),
('China','CN','CHN',156,'86','Yuan Renminbi','CNY','Chinese','zh'),
('Christmas Island','CX','CXR',162,'61','Australian Dollars','AUD','English','en'),
('Cocos (Keeling) Islands','CC','CCK',166,'61','Australian Dollars','AUD','English','en'),
('Colombia','CO','COL',170,'57','Peso','COP','Spanish','es'),
('Comoros','KM','COM',174,'269','Comoran Franc','KMF','French','fr'),
('Congo (Kinshasa)','CG','COG',178,'242','CFA Franc BEAC','XAF','French','fr'),
('Cook Islands','CK','COK',184,'682','New Zealand Dollars','NZD','English','en'),
('Costa Rica','CR','CRI',188,'506','Costa Rican Colon','CRC','Spanish','es'),
('Croatia (Hrvatska)','HR','HRV',191,'385','Croatian Dinar','HRK','English','en'),
('Cuba','CU','CUB',192,'53','Cuban Peso','CUP','Spanish','es'),
('Cyprus','CY','CYP',196,'357','Cypriot Pound','CYP','Greek','el'),
('Czech Republic','CZ','CZE',203,'420','Koruna','CZK','Czech','cs'),
('Democratic Republic of Congo','CD','COD',180,'243','Congolese Frank','CDF','French','fr'),
('Denmark','DK','DNK',208,'45','Danish Krone','DKK','Danish','da'),
('Djibouti','DJ','DJI',262,'253','Djiboutian Franc','DJF','French','fr'),
('Dominica','DM','DMA',212,'1-767','East Caribbean Dollar','XCD','English','en'),
('Dominican Republic','DO','DOM',214,'1-809,1-829,1-849','Dominican Peso','DOP','Spanish','es'),
('East Timor','TP','TLS',626,'670','Indonesian Rupiah','IDR','Portuguese','pt'),
('Ecuador','EC','ECU',218,'593','Sucre','ECS','Spanish','es'),
('Egypt','EG','EGY',818,'20','Egyptian Pound','EGP','Arabic','ar'),
('El Salvador','SV','SLV',222,'503','Salvadoran Colon','SVC','Spanish','es'),
('Equatorial Guinea','GQ','GNQ',226,'240','CFA Franc BEAC','XAF','Spanish','es'),
('Eritrea','ER','ERI',232,'291','Ethiopian Birr','ETB','Arabic','ar'),
('Estonia','EE','EST',233,'372','Estonian Kroon','EEK','Estonian','et'),
('Ethiopia','ET','ETH',231,'251','Ethiopian Birr','ETB','Amharic','am'),
('Falkland Islands (Malvinas)','FK','FLK',238,'500','Falkland Pound','FKP','English','en'),
('Faroe Islands','FO','FRO',234,'298','Danish Krone','DKK','English','en'),
('Fiji','FJ','FJI',242,'679','Fijian Dollar','FJD','English','en'),
('Finland','FI','FIN',246,'358','Euros','EUR','Finnish','fi'),
('France','FR','FRA',250,'33','Euros','EUR','French','fr'),
('French Guiana','GF','GUF',254,'594','Euros','EUR','French','fr'),
('French Polynesia','PF','PYF',258,'689','CFP Franc','XPF','French','fr'),
('French Southern Territories','TF','ATF',260,'262','Euros','EUR','French','fr'),
('Gabon','GA','GAB',266,'241','CFA Franc BEAC','XAF','French','fr'),
('Gambia','GM','GMB',270,'220','Dalasi','GMD','English','en'),
('Georgia','GE','GEO',268,'995','Lari','GEL','Georgian','ka'),
('Germany','DE','DEU',276,'49','Euros','EUR','German','de'),
('Ghana','GH','GHA',288,'233','Ghana cedi','GHS','English','en'),
('Gibraltar','GI','GIB',292,'350','Gibraltar Pound','GIP','English','en'),
('Greece','GR','GRC',300,'30','Euros','EUR','Greek','el'),
('Greenland','GL','GRL',304,'299','Danish Krone','DKK','English','en'),
('Grenada','GD','GRD',308,'1-473','East Caribbean Dollar','XCD','English','en'),
('Guadeloupe','GP','GLP',312,'590','Euros','EUR','French','fr'),
('Guam','GU','GUM',316,'1-671','USD','USD','English','en'),
('Guatemala','GT','GTM',320,'502','Quetzal','GTQ','Spanish','es'),
('Guernsey','GG','GGY',831,'44','Guernsey pound','GGP','English','en'),
('Guinea','GN','GIN',324,'224','Guinean Franc','GNF','French','fr'),
('Guinea-Bissau','GW','GNB',624,'245','CFA Franc BCEAO','XOF','Portuguese','pt'),
('Guyana','GY','GUY',328,'592','Guyanaese Dollar','GYD','English','en'),
('Haiti','HT','HTI',332,'509','Gourde','HTG','French','fr'),
('Heard and Mc Donald Islands','HM','HMD',334,'672','Australian Dollars','AUD','English','en'),
('Honduras','HN','HND',340,'504','Lempira','HNL','Spanish','es'),
('Hong Kong','HK','HKG',344,'852','HKD','HKD','Chinese','zh'),
('Hungary','HU','HUN',348,'36','Forint','HUF','Hungarian','hu'),
('Iceland','IS','ISL',352,'354','Icelandic Krona','ISK','Icelandic','is'),
('India','IN','IND',356,'91','Indian Rupee','INR','Hindi','hi'),
('Indonesia','ID','IDN',360,'62','Indonesian Rupiah','IDR','Indonesian','id'),
('Iran (Islamic Republic of)','IR','IRN',364,'98','Iranian Rial','IRR','Farsi','fa'),
('Iraq','IQ','IRQ',368,'964','Iraqi Dinar','IQD','Arabic','ar'),
('Ireland','IE','IRL',372,'353','Euros','EUR','English','en'),
('Isle of Man','IM','IMN',833,'44','Manx pound','GBP','English','en'),
('Israel','IL','ISR',376,'972','Shekel','ILS','Hebrew','he'),
('Italy','IT','ITA',380,'39','Euros','EUR','Italian','it'),
('Ivory Coast','CI','CIV',384,'225','CFA Franc BCEAO','XOF','French','fr'),
('Jamaica','JM','JAM',388,'1-876','Jamaican Dollar','JMD','English','en'),
('Japan','JP','JPN',392,'81','Japanese Yen','JPY','Japanese','ja'),
('Jersey','JE','JEY',832,'44','Sterling','GBP','Arabic','ar'),
('Jordan','JO','JOR',400,'962','Jordanian Dinar','JOD','Arabic','ar'),
('Kazakhstan','KZ','KAZ',398,'7','Tenge','KZT','Russian','ru'),
('Kenya','KE','KEN',404,'254','Kenyan Shilling','KES','English','en'),
('Kiribati','KI','KIR',296,'686','Australian Dollars','AUD','English','en'),
('Kuwait','KW','KWT',414,'965','Kuwaiti Dinar','KWD','Arabic','ar'),
('Kyrgyzstan','KG','KGZ',417,'996','Som','KGS','Russian','ru'),
('Lao People&apos;s Democratic Republic','LA','LAO',418,'856','Kip','LAK','Lao','lo'),
('Latvia','LV','LVA',428,'371','Lat','LVL','Latvian','lv'),
('Lebanon','LB','LBN',422,'961','Lebanese Pound','LBP','Arabic','ar'),
('Lesotho','LS','LSO',426,'266','Loti','LSL','English','en'),
('Liberia','LR','LBR',430,'231','Liberian Dollar','LRD','English','en'),
('Libya','LY','LBY',434,'218','Libyan Dinar','LYD','Arabic','ar'),
('Liechtenstein','LI','LIE',438,'423','Swiss Franc','CHF','German','de'),
('Lithuania','LT','LTU',440,'370','Lita','LTL','Lithuanian','lt'),
('Luxembourg','LU','LUX',442,'352','Euros','EUR','French','fr'),
('Macau','MO','MAC',446,'853','Pataca','MOP','Portuguese','pt'),
('Macedonia','MK','MKD',807,'389','Denar','MKD','Macedonian','en'),
('Madagascar','MG','MDG',450,'261','Malagasy Franc','MGA','French','fr'),
('Malawi','MW','MWI',454,'265','Malawian Kwacha','MWK','English','en'),
('Malaysia','MY','MYS',458,'60','Ringgit','MYR','English','en'),
('Maldives','MV','MDV',462,'960','Rufiyaa','MVR','English','en'),
('Mali','ML','MLI',466,'223','CFA Franc BCEAO','XOF','French','fr'),
('Malta','MT','MLT',470,'356','Maltese Lira','MTL','English','en'),
('Marshall Islands','MH','MHL',584,'692','USD','USD','English','en'),
('Martinique','MQ','MTQ',474,'596','Euros','EUR','French','fr'),
('Mauritania','MR','MRT',478,'222','Ouguiya','MRO','Arabic','ar'),
('Mauritius','MU','MUS',480,'230','Mauritian Rupee','MUR','English','en'),
('Mayotte','YT','MYT',175,'262','Euros','EUR','Greek','el'),
('Mexico','MX','MEX',484,'52','Peso','MXN','Spanish','es'),
('Micronesia Federated States of','FM','FSM',583,'691','USD','USD','Woleaian','en'),
('Moldova Republic of','MD','MDA',498,'373','Leu','MDL','Romanian','ro'),
('Monaco','MC','MCO',492,'377','Euros','EUR','French','fr'),
('Mongolia','MN','MNG',496,'976','Tugrik','MNT','Mongolian','mn'),
('Montenegro','ME','MNE',499,'382','Euro','EUR','Albanian','sq'),
('Montserrat','MS','MSR',500,'1-664','East Caribbean Dollar','XCD','Greek','el'),
('Morocco','MA','MAR',504,'212','Dirham','MAD','Arabic','ar'),
('Mozambique','MZ','MOZ',508,'258','Metical','MZN','Portuguese','pt'),
('Myanmar','MM','MMR',104,'95','Kyat','MMK','Burmese','my'),
('Namibia','NA','NAM',516,'264','Dollar','NAD','English','en'),
('Nauru','NR','NRU',520,'674','Australian Dollars','AUD','English','en'),
('Nepal','NP','NPL',524,'977','Nepalese Rupee','NPR','Nepali','ne'),
('Netherlands','NL','NLD',528,'31','Euros','EUR','English','en'),
('New Caledonia','NC','NCL',540,'687','CFP Franc','XPF','French','fr'),
('New Zealand','NZ','NZL',554,'64','New Zealand Dollars','NZD','English','en'),
('Nicaragua','NI','NIC',558,'505','Cordoba Oro','NIO','Spanish','es'),
('Niger','NE','NER',562,'227','CFA Franc BCEAO','XOF','French','fr'),
('Nigeria','NG','NGA',566,'234','Naira','NGN','English','en'),
('Niue','NU','NIU',570,'683','New Zealand Dollars','NZD','English','en'),
('Norfolk Island','NF','NFK',574,'672','Australian Dollars','AUD','English','en'),
('North Korea','KP','PRK',408,'850','Won','KPW','Korean','ko'),
('Northern Mariana Islands','MP','MNP',580,'1-670','USD','USD','English','en'),
('Norway','NO','NOR',578,'47','Norwegian Krone','NOK','Norwegian - Bokml','nb'),
('Oman','OM','OMN',512,'968','Sul Rial','OMR','Arabic','ar'),
('Pakistan','PK','PAK',586,'92','Rupee','PKR','English','en'),
('Palau','PW','PLW',585,'680','USD','USD','English','en'),
('Palestinian Territory','PS','PSE',275,'970','Jordanian dinar','JOD','Arabic','ar'),
('Panama','PA','PAN',591,'507','Balboa','PAB','Spanish','es'),
('Papua New Guinea','PG','PNG',598,'675','Kina','PGK','English','en'),
('Paraguay','PY','PRY',600,'595','Guarani','PYG','Spanish','es'),
('Peru','PE','PER',604,'51','Nuevo Sol','PEN','Spanish','es'),
('Philippines','PH','PHL',608,'63','Peso','PHP','English','en'),
('Pitcairn','PN','PCN',612,'870','New Zealand Dollars','NZD','English','en'),
('Poland','PL','POL',616,'48','Zloty','PLN','Polish','pl'),
('Portugal','PT','PRT',620,'351','Euros','EUR','Portuguese','pt'),
('Puerto Rico','PR','PRI',630,'1','USD','USD','Spanish','es'),
('Qatar','QA','QAT',634,'974','Rial','QAR','Arabic','ar'),
('Reunion','RE','REU',638,'262','Euros','EUR','French','fr'),
('Romania','RO','ROU',642,'40','Leu','RON','Romanian','ro'),
('Russian Federation','RU','RUS',643,'7','Ruble','RUB','Russian','ru'),
('Rwanda','RW','RWA',646,'250','Rwanda Franc','RWF','English','en'),
('Saint Barthelemy','BL','BLM',652,'590','Euro','EUR','French','fr'),
('Saint Helena','SH','SHN',654,'290','Saint Helena pound','GBP','English','en'),
('Saint Kitts and Nevis','KN','KNA',659,'1-869','East Caribbean Dollar','XCD','English','en'),
('Saint Lucia','LC','LCA',662,'1-758','East Caribbean Dollar','XCD','English','en'),
('Saint Martin (French part)','MF','MAF',663,'590','Netherlands Antillean guilder','ANG','French','fr'),
('Saint Pierre and Miquelon','PM','SPM',666,'508','Euro','EUR','English','en'),
('Saint Vincent and the Grenadines','VC','VCT',670,'1-784','East Caribbean Dollar','XCD','English','en'),
('Samoa','WS','WSM',882,'685','Euros','EUR','English','en'),
('San Marino','SM','SMR',674,'378','Euros','EUR','Italian','it'),
('Sao Tome and Principe','ST','STP',678,'239','Dobra','STD','Portuguese','pt'),
('Saudi Arabia','SA','SAU',682,'966','Riyal','SAR','Arabic','ar'),
('Senegal','SN','SEN',686,'221','CFA Franc BCEAO','XOF','French','fr'),
('Serbia','RS','SRB',688,'381','Serbian dinar','RSD','Serbian','sr'),
('Seychelles','SC','SYC',690,'248','Rupee','SCR','English','en'),
('Sierra Leone','SL','SLE',694,'232','Leone','SLL','English','en'),
('Singapore','SG','SGP',702,'65','Dollar','SGD','English','en'),
('Slovakia (Slovak Republic)','SK','SVK',703,'421','Koruna','SKK','Slovak','sk'),
('Slovenia','SI','SVN',705,'386','Euros','EUR','Slovenian','sl'),
('Solomon Islands','SB','SLB',90,'677','Solomon Islands Dollar','SBD','English','en'),
('Somalia','SO','SOM',706,'252','Shilling','SOS','English','en'),
('South Africa','ZA','ZAF',710,'27','Rand','ZAR','English','en'),
('South Georgia and the South Sandwich Islands','GS','SGS',239,'500','Sterling','GBP','English','en'),
('South Korea','KR','KOR',410,'82','Won','KRW','Korean','ko'),
('Spain','ES','ESP',724,'34','Euros','EUR','Spanish','es'),
('Sri Lanka','LK','LKA',144,'94','Rupee','LKR','English','en'),
('Sudan','SD','SDN',729,'249','Dinar','SDG','English','en'),
('Suriname','SR','SUR',740,'597','Surinamese Guilder','SRD','Arabic','ar'),
('Svalbard and Jan Mayen Islands','SJ','SJM',744,'47','Norwegian Krone','NOK','English','en'),
('Swaziland','SZ','SWZ',748,'268','Lilangeni','SZL','English','en'),
('Sweden','SE','SWE',752,'46','Krona','SEK','Swedish','sv'),
('Switzerland','CH','CHE',756,'41','Swiss Franc','CHF','French','fr'),
('Syrian Arab Republic','SY','SYR',760,'963','Syrian Pound','SYP','Arabic','ar'),
('Taiwan','TW','TWN',158,'886','Dollar','TWD','Chinese','zh'),
('Tajikistan','TJ','TJK',762,'992','Tajikistan Ruble','TJS','Russian','ru'),
('Tanzania','TZ','TZA',834,'255','Shilling','TZS','Arabic','ar'),
('Thailand','TH','THA',764,'66','Baht','THB','Thai','th'),
('Togo','TG','TGO',768,'228','CFA Franc BCEAO','XOF','French','fr'),
('Tokelau','TK','TKL',772,'690','New Zealand Dollars','NZD','English','en'),
('Tonga','TO','TON',776,'676','PaÕanga','TOP','English','en'),
('Trinidad and Tobago','TT','TTO',780,'1-868','Trinidad and Tobago Dollar','TTD','English','en'),
('Tunisia','TN','TUN',788,'216','Tunisian Dinar','TND','French','fr'),
('Turkey','TR','TUR',792,'90','Lira','TRY','Turkish','tr'),
('Turkmenistan','TM','TKM',795,'993','Manat','TMT','Turkmen','tk'),
('Turks and Caicos Islands','TC','TCA',796,'1-649','USD','USD','Turkmen','tk'),
('Tuvalu','TV','TUV',798,'688','Australian Dollars','AUD','English','en'),
('Uganda','UG','UGA',800,'256','Shilling','UGX','English','en'),
('Ukraine','UA','UKR',804,'380','Hryvnia','UAH','Ukrainian','uk'),
('United Arab Emirates','AE','ARE',784,'971','Dirham','AED','Arabic','ar'),
('United Kingdom','GB','GBR',826,'44','Sterling','GBP','English','en'),
('United States','US','USA',840,'1','USD','USD','English','en'),
('United States Minor Outlying Islands','UM','UMI',581,'1','USD','USD','English','en'),
('Uruguay','UY','URY',858,'598','Peso','UYU','Spanish','es'),
('Uzbekistan','UZ','UZB',860,'998','Som','UZS','Uzbek','uz'),
('Vanuatu','VU','VUT',548,'678','Vatu','VUV','English','en'),
('Venezuela','VE','VEN',862,'58','Bolivar','VEF','Spanish','es'),
('Vietnam','VN','VNM',704,'84','Dong','VND','Vietnamese','vi'),
('Virgin Islands (British)','VG','VGB',92,'1-284','USD','USD','English','en'),
('Virgin Islands (US)','VI','VIR',850,'1-340','USD','USD','English','en'),
('Wallis and Futuna Islands','WF','WLF',876,'681','CFP Franc','XPF','English','en'),
('Western Sahara','EH','ESH',732,'212','Dirham','MAD','English','en'),
('Yemen','YE','YEM',887,'967','Rial','YER','Arabic','ar'),
('Zambia','ZM','ZMB',894,'260','Kwacha','ZMK','English','en'),
('Zimbabwe','ZW','ZWE',716,'263','Zimbabwe Dollar','ZWD','English','en');

INSERT INTO regions (`name`, `country_id`)
VALUES ('Adamaoua',38),
('Centre',38),
('Est',38),
('Extréme-Nord',38),
('Littoral',38),
('Nord',38),
('North-West',38),
('Ouest',38),
('South-West',38),
('Sud',38);


INSERT INTO cities (`name`, `region_id`)
VALUES ('Douala',5),
('Yaounde',2),
('Bamenda',7),
('Garoua',6),
('Maroua',4),
('Bafoussam',8),
('Ngaoundere',1),
('Bertoua',3),
('Limbe',9),
('Edea',5),
('Kumba',9),
('Kumbo',7),
('Nkongsamba',5),
('Buea',9),
('Ebolowa',10),
('Bafang',8),
('Foumban',8),
('Guider',6),
('Mbalmayo',2),
('Meiganga',1),
('Bafia',2),
('Wum',7),
('Kribi',10),
('Batouri',3),
('Tibati',1),
('Belabo',3),
('Eseka',2),
('Abong Mbang',3),
('Kontcha',1),
('Aiyomojok',9),
('Mbe',6),
('Tiko',9),
('Muyuka',9),
('Mutengene',9),
('Ekona',9),
('Batoke',9);
